repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        description: Format files with cargo fmt.
        entry: cargo fmt --all -- --check --color always
        language: system
        types: [rust]
        args: ["--"]
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        description: Lint rust sources
        entry: cargo clippy
        language: system
        args: ["--all", "--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.5.1
    hooks:
      - id: validate_manifest

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
