[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.83"
homepage = "https://github.com/dstanek/stencil"
documentation = "https://github.com/dstanek/stencil"
repository = "https://github.com/dstanek/stencil"
authors = ["David Stanek <dstanek@dstanek.com"]
license = "MIT"