[package]
name = "stencil"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
serde = { version = "1.0.213", features = ["derive"] }
thiserror = "1.0.65"
toml = "0.8.19"
