[package]
name = "stencil"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
clap = { version = "4.5.20", features = ["derive"] }
liquid = "0.26.9"
serde = { version = "1.0.213", features = ["derive"] }
similar = "2.6.0"
termcolor = "1.4.1"
thiserror = "1.0.65"
toml = "0.8.19"
