[workspace]
members = [
    "crates/*"
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.83"
homepage = "https://github.com/dstanek/stencil"
documentation = "https://github.com/dstanek/stencil"
repository = "https://github.com/dstanek/stencil"
authors = ["David Stanek <dstanek@dstanek.com"]
license = "MIT"

[workspace.dependencies]
stencil-error = { path = "crates/stencil-error" }
stencil-source = { path = "crates/stencil-source" }

serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "1.0.65"
toml = "0.8.19"
ureq = { version = "3.0.4", features = ["json"] }
